### ISSUE TITLE
可以用android手机或者iOS手机连接云手机吗？

### ISSUE THREAD

**Issue by VZaneFu** [DockDroid/openvmi#5]

**Comment by maxingrong1213** [comment]
开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DockDroid/openvmi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 下午3:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5)

**Comment by VZaneFu** [comment]
开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。

你们连接云手机用的什么方式或者说协议？

**Comment by VZaneFu** [comment]
> 开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DockDroid/openvmi" ***@***.***&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 下午3:57 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你们连接云手机用的什么方式或者说协议？
@maxingrong1213

**Comment by VZaneFu** [comment]
> 开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DockDroid/openvmi" ***@***.***&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 下午3:57 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

如果不想用你们的APP，我想嵌入到我的APP里面，可以实现吗？

**Comment by maxingrong1213** [comment]
连接方式采用的是我们自己开发的串流协议，视频h264 音频aac 包括触控、重力传感器、gps等真机功能都有做在了串流协议里面。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5)





  
开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DockDroid/openvmi" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 下午3:57 @.&gt;; @.***&gt;; 主题:&nbsp;[DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你们连接云手机用的什么方式或者说协议？
 @maxingrong1213

**Comment by maxingrong1213** [comment]
您是说您有自己的串流协议是吗？那也可以的，适配到我们的云机系统里来就可以。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5)





  
开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DockDroid/openvmi" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 下午3:57 @.&gt;; @.***&gt;; 主题:&nbsp;[DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
如果不想用你们的APP，我想嵌入到我的APP里面，可以实现吗？

**Comment by maxingrong1213** [comment]
您可以加我的微信讨论，18252585792




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5)





  
开源的openvmi版本没用提供此功能，在我们的商用版本中有能够安装在客户的Android手机和ISO里的APP，可以连接到云手机。我们目前云手机做的很稳定流畅，如果有需要您也可以跟我们合作。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DockDroid/openvmi" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 下午3:57 @.&gt;; @.***&gt;; 主题:&nbsp;[DockDroid/openvmi] 可以用android手机或者iOS手机连接云手机吗？ (#5) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
如果不想用你们的APP，我想嵌入到我的APP里面，可以实现吗？
